In [31]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [64]:
from modules.data_generator import make_data
from pathlib import Path
import pandas as pd
import sys

ROOT = Path('data_generator_example.ipynb').parent
sys.path.insert(0, str(ROOT))

In [66]:
data = make_data(
    n_med = 5000, n_id = 0, n_overlap = 0, 
    config = 'default_config'
)
data[['smoker', 'hbp']] = data[['smoker', 'hbp']].astype(bool)
data = data.reset_index(drop=True)  # n_id = 387_000 (for copula and bayesian network)
data

     address  age                sex conditions  smoker    hbp
0        T3H   17               male        N/A   False  False
1        T2B    0               male        N/A   False  False
2        T1Y    2             female        Q56   False  False
3        T1Y   13             female        Q02   False  False
4        T3A   14             female        N/A   False  False
...      ...  ...                ...        ...     ...    ...
4995     T3E    9             female        N/A   False   True
4996     T3A   24  prefer not to say        N/A   False  False
4997     T3E   23  prefer not to say        N/A   False  False
4998     T2K   18               male        Q22   False  False
4999     T1P   15             female        Q51   False  False

[5000 rows x 6 columns]

In [67]:
data.to_csv('data/calgary_kids.csv')

In [69]:
data2 = data.iloc[:,1:]
data2

      age                sex conditions  smoker    hbp
0      17               male        N/A   False  False
1       0               male        N/A   False  False
2       2             female        Q56   False  False
3      13             female        Q02   False  False
4      14             female        N/A   False  False
...   ...                ...        ...     ...    ...
4995    9             female        N/A   False   True
4996   24  prefer not to say        N/A   False  False
4997   23  prefer not to say        N/A   False  False
4998   18               male        Q22   False  False
4999   15             female        Q51   False  False

[5000 rows x 5 columns]

In [70]:
# Bin ages into 5-year left-closed brackets: [0,5), [5,10), ..., [20,25)
age_bins = pd.IntervalIndex.from_breaks([0, 5, 10, 15, 20, 25], closed='left')
data2['age'] = pd.cut(data2['age'], age_bins)
data2

           age                sex conditions  smoker    hbp
0     [15, 20)               male        N/A   False  False
1       [0, 5)               male        N/A   False  False
2       [0, 5)             female        Q56   False  False
3     [10, 15)             female        Q02   False  False
4     [10, 15)             female        N/A   False  False
...        ...                ...        ...     ...    ...
4995   [5, 10)             female        N/A   False   True
4996  [20, 25)  prefer not to say        N/A   False  False
4997  [20, 25)  prefer not to say        N/A   False  False
4998  [15, 20)               male        Q22   False  False
4999  [15, 20)             female        Q51   False  False

[5000 rows x 5 columns]

In [74]:
data2.to_csv('data/calgary_kids_recommendations.csv', index=False)