In [144]:
%pip install names

Requirement already satisfied: names in /opt/conda/lib/python3.13/site-packages (0.3.0)
Note: you may need to restart the kernel to use updated packages.

In [156]:
import random 
import numpy as np
import pandas as pd
import names

In [175]:
def smoking(n):
    p = 0.11
    smoke_yn = random.choices(["yes","no"], [p, 1-p], k=n)
    return(smoke_yn)

In [176]:
def sample_province(n):
    provinces = ["ON","QB","BC", "AB" , "MB", "SK", "NS", "NB", "NL", "PEI", "NWT", "YK", "NV"]
    weights = [0.3845, 0.2298, 0.1352, 0.1152, 0.0363, 0.0306,0.0262, 0.0209, 0.0138, 0.0042, 0.0011, 0.0011, 0.0010]
    results = random.choices(provinces, weights=weights, k=n)
    return(results)

In [177]:
def gender(n):
    p = 0.05
    gend = random.choices(["male","female","other"], [(1-p)/2, (1-p)/2, p], k=n)
    return(gend)

In [178]:
def cancer(n):
    p = 0.05
    gend = random.choices(["yes","no",], [p, 1-p], k=n)
    return(gend)

In [220]:
def depression_score(n):
    dep = np.random.poisson(lam=3, size=n)
    return(dep*10)

In [221]:
def dataset_1(n):
    smoke = smoking(n)
    gend = gender(n)
    last_names = [None]*n
    for i in range(n-1):
        last_names[i] =names.get_last_name()
    prov = sample_province(n)
    data1 = np.column_stack((last_names,prov,gend, smoke))
    return(data1)

In [222]:
def dataset_2(data1,n,k):
    #data_1 = an array generated by dataset_1
    # n = number of entries in dataset_2 
    # k = number of overlapping entries between dataset 1 and dataset 2 
    # k < n and k > length(data1)
    if k > n:
        return("k must be smaller than or equal to n")
    elif k > len(data1):
        return("k must be smaller than or equal to the number of entries in data1")
    else:
        # Randomly select the overlapping data between the two datasets
        rng = np.random.default_rng()
        ints = random.sample(range(0, len(data1)), k)
        mat1 = data1[ints]
        # Transform the existing data into the correct form for dataset 2
        # Remove name column and province column
        mat1 = mat1[:, 2:len(data1)-1]
        # Add cancer data and depression data
        canc1 = ["yes"]*k
        dep1 = depression_score(k)
        mat2 = np.column_stack((mat1, canc1, dep1))
        # Generate new data for dataset 2
        gend = gender(n-k)
        smoke = smoking(n-k)
        canc2= cancer(n-k)
        dep2 = depression_score(n-k)
        mat3 = np.column_stack((gend, smoke, canc2, dep2))
        # Combine existing data with new data and scramble the rows 
        result1 = np.vstack([mat2, mat3])
        rng = np.random.default_rng()
        result2 = rng.permutation(result1)
        return(result2)

In [223]:
def create_data(n1,n2,k):
    #n1 = number of individuals in dataset 1 
    #n2 = number of individuals in dataset 2
    #k = number of overlapping individuals
    if k > n1:
        return("k must be smaller than or equal to n1")
    elif k > n2:
        return("k must be smaller than or equal to n2")
    else:  
        data1 = dataset_1(n1)
        data2 = dataset_2(data1, n2,k)
        df1 = pd.DataFrame(data1, columns=['Last Name','Province','Gender', 'Smokes'])
        df2 = pd.DataFrame(data2, columns = ['Gender', 'Smokes', 'Has cancer', 'Depression Score'])
        return(df1,df2)

In [224]:
data1, data2 = create_data(40,30,10)

In [225]:
data1

     Last Name Province  Gender Smokes
0        Jones       BC  female     no
1       Anklam       ON  female     no
2       Elwell       QB   other     no
3     Sprinkle       NB    male     no
4   Williamson       QB  female     no
5      Sandage       ON    male    yes
6    Mccormick       QB  female     no
7      Kindred       BC    male     no
8        Smith       AB  female     no
9        Tubbs       BC    male     no
10        Hunt       ON    male     no
11  Wisniewski       BC  female     no
12       Davis       ON    male     no
13       Lysak       ON    male     no
14       Moses       ON    male    yes
15       Gross       ON  female     no
16     Collins       ON  female     no
17    Washburn       QB    male     no
18     Jenkins       MB   other    yes
19       Olsen       QB  female    yes
20    Mcmurtry       QB  female     no
21       Josey       ON    male     no
22        Hurt       ON    male     no
23   Sheffield       SK  female     no
24       Crews       AB  female     no
25    Williams       QB    male     no
26       Ardis       ON  female     no
27    Martinez       ON    male     no
28       Evans       AB    male     no
29       Gates       ON    male     no
30     Michael       QB  female     no
31     Grunder       QB  female     no
32       Allen       QB   other     no
33   Strayhorn       QB    male     no
34   Feliciano       ON  female     no
35       Owens       BC    male     no
36         Rey       MB    male     no
37      Zmolek       BC  female     no
38        Bona       ON  female    yes
39        None       ON  female     no

In [226]:
data2

    Gender Smokes Has cancer Depression Score
0   female    yes        yes                0
1     male     no         no               40
2     male     no        yes               30
3     male     no         no               50
4   female     no        yes               60
5    other     no         no               10
6    other     no         no               50
7   female     no        yes               20
8   female     no        yes               10
9   female     no        yes               20
10    male     no         no               40
11  female    yes        yes               50
12  female     no         no               10
13  female     no        yes               40
14   other    yes        yes               30
15  female     no         no               30
16    male     no         no               40
17    male     no        yes               50
18  female     no        yes                0
19   other     no         no               50
20    male     no         no               40
21  female     no         no               30
22    male     no         no               20
23  female     no         no               50
24    male     no         no               40
25    male     no        yes               50
26    male     no         no               40
27    male     no         no               20
28  female     no         no               10
29    male     no         no               10

In [227]:
data1.to_csv('data1.csv', index=False)
data2.to_csv('data2.csv', index = False)